[package]
name = "images"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_egui = { package = "bevy_egui", version = "0.33" }
num = "0.4"
image = "0.25"
bevy = "0.15"
rfd = "0.15"

crossbeam-channel = "0.5.14"
